package auviotre.enigmatic.legacy.registries;

import auviotre.enigmatic.legacy.EnigmaticLegacy;
import auviotre.enigmatic.legacy.api.item.IAmulet;
import auviotre.enigmatic.legacy.api.item.IItemHelper;
import auviotre.enigmatic.legacy.contents.item.amulets.AscensionAmulet;
import auviotre.enigmatic.legacy.contents.item.amulets.EldritchAmulet;
import auviotre.enigmatic.legacy.contents.item.amulets.EnigmaticAmulet;
import auviotre.enigmatic.legacy.contents.item.amulets.UnwitnessedAmulet;
import auviotre.enigmatic.legacy.contents.item.books.*;
import auviotre.enigmatic.legacy.contents.item.charms.*;
import auviotre.enigmatic.legacy.contents.item.etherium.EtheriumArmor;
import auviotre.enigmatic.legacy.contents.item.etherium.EtheriumHammer;
import auviotre.enigmatic.legacy.contents.item.etherium.EtheriumScythe;
import auviotre.enigmatic.legacy.contents.item.etherium.EtheriumSword;
import auviotre.enigmatic.legacy.contents.item.food.AstralFruit;
import auviotre.enigmatic.legacy.contents.item.food.Exterminato;
import auviotre.enigmatic.legacy.contents.item.food.ForbiddenFruit;
import auviotre.enigmatic.legacy.contents.item.food.Ichoroot;
import auviotre.enigmatic.legacy.contents.item.generic.BaseCursedItem;
import auviotre.enigmatic.legacy.contents.item.generic.BaseItem;
import auviotre.enigmatic.legacy.contents.item.legacy.*;
import auviotre.enigmatic.legacy.contents.item.materials.*;
import auviotre.enigmatic.legacy.contents.item.misc.*;
import auviotre.enigmatic.legacy.contents.item.op.LootGenerator;
import auviotre.enigmatic.legacy.contents.item.op.TheJudgement;
import auviotre.enigmatic.legacy.contents.item.potions.*;
import auviotre.enigmatic.legacy.contents.item.rings.*;
import auviotre.enigmatic.legacy.contents.item.scrolls.*;
import auviotre.enigmatic.legacy.contents.item.spellstones.*;
import auviotre.enigmatic.legacy.contents.item.spellstones.other.Spellcore;
import auviotre.enigmatic.legacy.contents.item.spellstones.other.SpellstoneSword;
import auviotre.enigmatic.legacy.contents.item.spellstones.other.Spelltuner;
import auviotre.enigmatic.legacy.contents.item.tools.*;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

public class EnigmaticItems {
    public static final List<DeferredItem<? extends Item>> TAB_ACCEPT_LIST = new ArrayList<>();
    public static final List<DeferredItem<? extends Item>> CTAB_ACCEPT_LIST = new ArrayList<>();
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(EnigmaticLegacy.MODID);
    public static final DeferredItem<TheAcknowledgment> THE_ACKNOWLEDGMENT = registerWithTab("the_acknowledgment", TheAcknowledgment::new);
    public static final DeferredItem<UnwitnessedAmulet> UNWITNESSED_AMULET = registerWithTab("unwitnessed_amulet", UnwitnessedAmulet::new);
    public static final DeferredItem<EnigmaticAmulet> ENIGMATIC_AMULET_RED = registerWithTab("enigmatic_amulet_red", () -> new EnigmaticAmulet(IAmulet.Color.RED));
    public static final DeferredItem<EnigmaticAmulet> ENIGMATIC_AMULET_AQUA = registerWithTab("enigmatic_amulet_aqua", () -> new EnigmaticAmulet(IAmulet.Color.AQUA));
    public static final DeferredItem<EnigmaticAmulet> ENIGMATIC_AMULET_VIOLET = registerWithTab("enigmatic_amulet_violet", () -> new EnigmaticAmulet(IAmulet.Color.VIOLET));
    public static final DeferredItem<EnigmaticAmulet> ENIGMATIC_AMULET_MAGENTA = registerWithTab("enigmatic_amulet_magenta", () -> new EnigmaticAmulet(IAmulet.Color.MAGENTA));
    public static final DeferredItem<EnigmaticAmulet> ENIGMATIC_AMULET_GREEN = registerWithTab("enigmatic_amulet_green", () -> new EnigmaticAmulet(IAmulet.Color.GREEN));
    public static final DeferredItem<EnigmaticAmulet> ENIGMATIC_AMULET_BLACK = registerWithTab("enigmatic_amulet_black", () -> new EnigmaticAmulet(IAmulet.Color.BLACK));
    public static final DeferredItem<EnigmaticAmulet> ENIGMATIC_AMULET_BLUE = registerWithTab("enigmatic_amulet_blue", () -> new EnigmaticAmulet(IAmulet.Color.BLUE));
    public static final DeferredItem<Item> SPELLSTONE_DEBRIS = registerWithTab("spellstone_debris", () -> new Item(IItemHelper.properties(32).rarity(Rarity.UNCOMMON).fireResistant()));
    public static final DeferredItem<Spellcore> SPELLCORE = registerWithTab("spellcore", Spellcore::new);
    public static final DeferredItem<Spelltuner> SPELLTUNER = registerWithTab("spelltuner", Spelltuner::new);
    public static final DeferredItem<SpellstoneSword> SPELLSTONE_SWORD = registerWithTab("spellstone_sword", SpellstoneSword::new);
    public static final DeferredItem<GolemHeart> GOLEM_HEART = registerWithTab("golem_heart", GolemHeart::new);
    public static final DeferredItem<BlazingCore> BLAZING_CORE = registerWithTab("blazing_core", BlazingCore::new);
    public static final DeferredItem<OceanStone> OCEAN_STONE = registerWithTab("ocean_stone", OceanStone::new);
    public static final DeferredItem<AngelBlessing> ANGEL_BLESSING = registerWithTab("angel_blessing", AngelBlessing::new);
    public static final DeferredItem<EyeOfNebula> EYE_OF_NEBULA = registerWithTab("eye_of_nebula", EyeOfNebula::new);
    public static final DeferredItem<VoidPearl> VOID_PEARL = registerWithTab("void_pearl", VoidPearl::new);
    public static final DeferredItem<ForgottenIce> FORGOTTEN_ICE = registerWithTab("forgotten_ice", ForgottenIce::new);
    public static final DeferredItem<RevivalLeaf> REVIVAL_LEAF = registerWithTab("revival_leaf", RevivalLeaf::new);
    public static final DeferredItem<LostEngine> LOST_ENGINE = registerWithTab("lost_engine", LostEngine::new);
    public static final DeferredItem<IllusionLantern> ILLUSION_LANTERN = registerWithTab("illusion_lantern", IllusionLantern::new);
    public static final DeferredItem<EtheriumCore> ETHERIUM_CORE = registerWithTab("etherium_core", EtheriumCore::new);
    public static final DeferredItem<TheCube> THE_CUBE = registerWithTab("the_cube", TheCube::new);
    public static final DeferredItem<CreationHeart> CREATION_HEART = registerWithTab("creation_heart", CreationHeart::new);
    public static final DeferredItem<IronRing> IRON_RING = registerWithTab("iron_ring", IronRing::new);
    public static final DeferredItem<GoldenRing> GOLDEN_RING = registerWithTab("golden_ring", GoldenRing::new);
    public static final DeferredItem<MinerRing> MINER_RING = registerWithTab("miner_ring", MinerRing::new);
    public static final DeferredItem<MagnetRing> MAGNET_RING = registerWithTab("magnet_ring", MagnetRing::new);
    public static final DeferredItem<QuartzRing> QUARTZ_RING = registerWithTab("quartz_ring", QuartzRing::new);
    public static final DeferredItem<EnderRing> ENDER_RING = registerWithTab("ender_ring", EnderRing::new);
    public static final DeferredItem<DislocationRing> DISLOCATION_RING = registerWithTab("dislocation_ring", DislocationRing::new);
    public static final DeferredItem<InfernalRing> INFERNAL_RING = registerWithTab("infernal_ring", InfernalRing::new);
    public static final DeferredItem<Item> STARLIGHT_RING = registerWithTab("starlight_ring", StarlightRing::new);
    public static final DeferredItem<Item> BLANK_SCROLL = registerWithTab("blank_scroll", () -> new Item(IItemHelper.properties(16)));
    public static final DeferredItem<SurvivorScroll> SURVIVOR_SCROLL = registerWithTab("survivor_scroll", SurvivorScroll::new);
    public static final DeferredItem<ExplorerScroll> EXPLORER_SCROLL = registerWithTab("explorer_scroll", ExplorerScroll::new);
    public static final DeferredItem<HunterScroll> HUNTER_SCROLL = registerWithTab("hunter_scroll", HunterScroll::new);
    public static final DeferredItem<XpScroll> XP_SCROLL = registerWithTab("xp_scroll", XpScroll::new);
    public static final DeferredItem<EscapeScroll> ESCAPE_SCROLL = registerWithTab("escape_scroll", EscapeScroll::new);
    public static final DeferredItem<HeavenScroll> HEAVEN_SCROLL = registerWithTab("heaven_scroll", HeavenScroll::new);
    public static final DeferredItem<FabulousScroll> FABULOUS_SCROLL = registerWithTab("fabulous_scroll", FabulousScroll::new);
    public static final DeferredItem<CosmicScroll> COSMIC_SCROLL = registerWithTab("cosmic_scroll", CosmicScroll::new);
    public static final DeferredItem<AnimalGuidebook> ANIMAL_GUIDEBOOK = registerWithTab("animal_guidebook", AnimalGuidebook::new);
    public static final DeferredItem<HunterGuidebook> HUNTER_GUIDEBOOK = registerWithTab("hunter_guidebook", HunterGuidebook::new);
    public static final DeferredItem<LivingOde> ODE_TO_LIVING = registerWithTab("ode_to_living", LivingOde::new);
    public static final DeferredItem<EnchantmentTransposer> ENCHANTMENT_TRANSPOSER = registerWithTab("enchantment_transposer", EnchantmentTransposer::new);
    public static final DeferredItem<ExtradimensionalEye> EXTRADIMENSIONAL_EYE = registerWithTab("extradimensional_eye", ExtradimensionalEye::new);
    public static final DeferredItem<Infinimeal> INFINIMEAL = registerWithTab("infinimeal", Infinimeal::new);
    public static final DeferredItem<RecallPotion> RECALL_POTION = registerWithTab("recall_potion", RecallPotion::new);
    public static final DeferredItem<WormholePotion> WORMHOLE_POTION = registerWithTab("wormhole_potion", WormholePotion::new);
    public static final DeferredItem<MendingMixture> MENDING_MIXTURE = registerWithTab("mending_mixture", MendingMixture::new);
    public static final DeferredItem<MiningCharm> MINING_CHARM = registerWithTab("mining_charm", MiningCharm::new);
    public static final DeferredItem<MonsterCharm> MONSTER_CHARM = registerWithTab("monster_charm", MonsterCharm::new);
    public static final DeferredItem<EnigmaticEye> ENIGMATIC_EYE = registerWithTab("enigmatic_eye", EnigmaticEye::new);
    public static final DeferredItem<ForgerGem> FORGER_GEM = registerWithTab("forger_gem", ForgerGem::new);
    public static final DeferredItem<EarthHeart> EARTH_HEART = registerWithTab("earth_heart", EarthHeart::new);
    public static final DeferredItem<EarthHeart.Fragment> EARTH_HEART_FRAGMENT = registerWithTab("earth_heart_fragment", EarthHeart.Fragment::new);
    public static final DeferredItem<Item> INFERNAL_CINDER = registerWithTab("infernal_cinder", BaseItem::new);
    public static final DeferredItem<Exterminato> EXTERMINATO = registerWithTab("exterminato", Exterminato::new);
    public static final DeferredItem<InfernalSpear> INFERNAL_SPEAR = registerWithTab("infernal_spear", InfernalSpear::new);
    public static final DeferredItem<Item> INFERNAL_FISHING_ROD = registerWithTab("infernal_fishing_rod", BaseItem::Unknown);
    public static final DeferredItem<ExecutionAxe> EXECUTION_AXE = registerWithTab("execution_axe", ExecutionAxe::new);
    public static final DeferredItem<HellBladeCharm> HELL_BLADE_CHARM = registerWithTab("hell_blade_charm", HellBladeCharm::new);
    public static final DeferredItem<Item> ICHOR_DROPLET = registerWithTab("ichor_droplet", BaseItem::new);
    public static final DeferredItem<Ichoroot> ICHOROOT = registerWithTab("ichoroot", Ichoroot::new);
    public static final DeferredItem<IchorSpear> ICHOR_SPEAR = registerWithTab("ichor_spear", IchorSpear::new);
    public static final DeferredItem<IchorBottle> ICHOR_BOTTLE = registerWithTab("ichor_bottle", () -> new IchorBottle(false));
    public static final DeferredItem<UnholyGrail> UNHOLY_GRAIL = registerWithTab("unholy_grail", UnholyGrail::new);
    public static final DeferredItem<VoidStone> VOID_STONE = registerWithTab("void_stone", VoidStone::new);
    public static final DeferredItem<VoidTome> VOID_TOME = registerWithTab("void_tome", VoidTome::new);
    public static final DeferredItem<ForbiddenFruit> FORBIDDEN_FRUIT = registerWithTab("forbidden_fruit", ForbiddenFruit::new);
    public static final DeferredItem<ForbiddenJuice> FORBIDDEN_JUICE = registerWithTab("forbidden_juice", ForbiddenJuice::new);
    public static final DeferredItem<RedemptionPotion> REDEMPTION_POTION = registerWithTab("redemption_potion", RedemptionPotion::new);
    public static final DeferredItem<AntiqueBag> ANTIQUE_BAG = registerWithTab("antique_bag", AntiqueBag::new);
    public static final DeferredItem<LoreInscriber> LORE_INSCRIBER = registerWithTab("lore_inscriber", LoreInscriber::new);
    public static final DeferredItem<LoreInscriber.Fragment> LORE_FRAGMENT = registerWithTab("lore_fragment", LoreInscriber.Fragment::new);
    public static final DeferredItem<Item> ASTRAL_DUST = registerWithTab("astral_dust", BaseItem::new);
    public static final DeferredItem<AstralFruit> ASTRAL_FRUIT = registerWithTab("astral_fruit", () -> new AstralFruit(false));
    public static final DeferredItem<Item> ENDER_ROD = registerWithTab("ender_rod", BaseItem::new);
    public static final DeferredItem<Item> RAW_ETHERIUM = registerWithTab("raw_etherium", () -> new Item(IItemHelper.properties().fireResistant()));
    public static final DeferredItem<Item> ETHERIUM_INGOT = registerWithTab("etherium_ingot", () -> new Item(IItemHelper.properties().fireResistant()));
    public static final DeferredItem<Item> ETHERIUM_NUGGET = registerWithTab("etherium_nugget", () -> new Item(IItemHelper.properties().fireResistant()));
    public static final DeferredItem<EtheriumSword> ETHERIUM_SWORD = registerWithTab("etherium_sword", EtheriumSword::new);
    public static final DeferredItem<EtheriumHammer> ETHERIUM_HAMMER = registerWithTab("etherium_hammer", EtheriumHammer::new);
    public static final DeferredItem<EtheriumScythe> ETHERIUM_SCYTHE = registerWithTab("etherium_scythe", EtheriumScythe::new);
    public static final DeferredItem<EtheriumArmor> ETHERIUM_HELMET = registerWithTab("etherium_helmet", () -> new EtheriumArmor(ArmorItem.Type.HELMET));
    public static final DeferredItem<EtheriumArmor> ETHERIUM_CHESTPLATE = registerWithTab("etherium_chestplate", () -> new EtheriumArmor(ArmorItem.Type.CHESTPLATE));
    public static final DeferredItem<EtheriumArmor> ETHERIUM_LEGGINGS = registerWithTab("etherium_leggings", () -> new EtheriumArmor(ArmorItem.Type.LEGGINGS));
    public static final DeferredItem<EtheriumArmor> ETHERIUM_BOOTS = registerWithTab("etherium_boots", () -> new EtheriumArmor(ArmorItem.Type.BOOTS));
    public static final DeferredItem<EtherealForgingCharm> ETHEREAL_FORGING_CHARM = registerWithTab("ethereal_forging_charm", EtherealForgingCharm::new);
    public static final DeferredItem<MajesticElytra> MAJESTIC_ELYTRA = registerWithTab("majestic_elytra", MajesticElytra::new);
    public static final DeferredItem<DragonBreathBow> DRAGON_BREATH_BOW = registerWithTab("dragon_breath_bow", DragonBreathBow::new);
    public static final DeferredItem<Item> COSMIC_HEART = registerWithTab("cosmic_heart", () -> new Item(IItemHelper.properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<StarlightParticle> STARLIGHT_PARTICLE = registerWithTab("starlight_particle", StarlightParticle::new);
    public static final DeferredItem<StarlightParticle> STARLIGHT_INGOT = registerWithTab("starlight_ingot", StarlightParticle::new);
    public static final DeferredItem<StarlightBucket> STARLIGHT_BUCKET = registerWithTab("starlight_bucket", StarlightBucket::new);
    public static final DeferredItem<StarlightPearl> STARLIGHT_PEARL = registerWithTab("starlight_pearl", StarlightPearl::new);
    public static final DeferredItem<AscensionAmulet> ASCENSION_AMULET = registerWithTab("ascension_amulet", AscensionAmulet::new);
    public static final DeferredItem<Item> ASTRAL_SPEAR = registerWithTab("astral_spear", BaseItem::Unknown);
    public static final DeferredItem<CursedRing> CURSED_RING = registerWithCTab("cursed_ring", CursedRing::new);
    public static final DeferredItem<TwistedHeart> TWISTED_HEART = registerWithCTab("twisted_heart", TwistedHeart::new);
    public static final DeferredItem<TwistedMirror> TWISTED_MIRROR = registerWithCTab("twisted_mirror", TwistedMirror::new);
    public static final DeferredItem<TwistedPotion> TWISTED_POTION = registerWithCTab("twisted_potion", TwistedPotion::new);
    public static final DeferredItem<InfernalShield> INFERNAL_SHIELD = registerWithCTab("infernal_shield", InfernalShield::new);
    public static final DeferredItem<BerserkEmblem> BERSERK_EMBLEM = registerWithCTab("berserk_emblem", BerserkEmblem::new);
    public static final DeferredItem<SanguinaryHandbook> SANGUINARY_HANDBOOK = registerWithCTab("sanguinary_handbook", SanguinaryHandbook::new);
    public static final DeferredItem<CursedStone> CURSED_STONE = registerWithCTab("cursed_stone", CursedStone::new);
    public static final DeferredItem<FalseJustice> FALSE_JUSTICE = registerWithCTab("false_justice", FalseJustice::new);
    public static final DeferredItem<SoulCompass> SOUL_COMPASS = registerWithCTab("soul_compass", SoulCompass::new);
    public static final DeferredItem<Item> EVIL_ESSENCE = registerWithCTab("evil_essence", EvilEssence::new);
    public static final DeferredItem<Item> EVIL_INGOT = registerWithCTab("evil_ingot", () -> new BaseCursedItem(IItemHelper.properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<TheTwist> THE_TWIST = registerWithCTab("the_twist", TheTwist::new);
    public static final DeferredItem<CurseTransposer> CURSE_TRANSPOSER = registerWithCTab("curse_transposer", CurseTransposer::new);
    public static final DeferredItem<TotemOfMalice> TOTEM_OF_MALICE = registerWithCTab("totem_of_malice", TotemOfMalice::new);
    public static final DeferredItem<EnchanterPearl> ENCHANTER_PEARL = registerWithCTab("enchanter_pearl", EnchanterPearl::new);
    public static final DeferredItem<EnderSlayer> ENDER_SLAYER = registerWithCTab("ender_slayer", EnderSlayer::new);
    public static final DeferredItem<GuardianHeart> GUARDIAN_HEART = registerWithCTab("guardian_heart", GuardianHeart::new);
    public static final DeferredItem<AstralFruit> ENCHANTED_ASTRAL_FRUIT = registerWithCTab("enchanted_astral_fruit", () -> new AstralFruit(true));
    public static final DeferredItem<RedemptionRing> REDEMPTION_RING = registerWithCTab("redemption_ring", RedemptionRing::new);
    public static final DeferredItem<PureHeart> PURE_HEART = registerWithCTab("pure_heart", PureHeart::new);
    public static final DeferredItem<Item> BLESS_ITEM = registerWithCTab("bless_item", BaseItem::Unknown);
    public static final DeferredItem<BlessPotion> BLESS_POTION = registerWithCTab("bless_potion", BlessPotion::new);
    public static final DeferredItem<IchorCurseBottle> ICHOR_CURSE_BOTTLE = registerWithCTab("ichor_curse_bottle", IchorCurseBottle::new);
    public static final DeferredItem<Item> SACRED_CRYSTAL = registerWithCTab("sacred_crystal", () -> new BaseCursedItem(IItemHelper.properties(16).rarity(Rarity.UNCOMMON), true));
    public static final DeferredItem<TheBless> THE_BLESS = registerWithCTab("the_bless", TheBless::new);
    public static final DeferredItem<BlessAmplifier> BLESS_AMPLIFIER = registerWithCTab("bless_amplifier", BlessAmplifier::new);
    public static final DeferredItem<Item> GRAIL = registerWithCTab("grail", BaseItem::Unknown);
    public static final DeferredItem<Item> FORGER_CRYSTAL = registerWithCTab("forger_crystal", BaseItem::Unknown);
    public static final DeferredItem<ScorchedCharm> SCORCHED_CHARM = registerWithCTab("scorched_charm", ScorchedCharm::new);
    public static final DeferredItem<EarthPromise> EARTH_PROMISE = registerWithCTab("earth_promise", EarthPromise::new);
    public static final DeferredItem<BlessStone> BLESS_STONE = registerWithCTab("bless_stone", BlessStone::new);
    public static final DeferredItem<IchorBottle> ENCHANTED_ICHOR_BOTTLE = registerWithCTab("enchanted_ichor_bottle", () -> new IchorBottle(true));
    public static final DeferredItem<Item> DARKEST_SCROLL = registerWithCTab("darkest_scroll", () -> new Item(IItemHelper.properties(16).rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<NightScroll> NIGHT_SCROLL = registerWithCTab("night_scroll", NightScroll::new);
    public static final DeferredItem<CursedScroll> CURSED_SCROLL = registerWithCTab("cursed_scroll", CursedScroll::new);
    public static final DeferredItem<AvariceScroll> AVARICE_SCROLL = registerWithCTab("avarice_scroll", AvariceScroll::new);
    public static final DeferredItem<CursedXpScroll> CURSED_XP_SCROLL = registerWithCTab("cursed_xp_scroll", CursedXpScroll::new);
    public static final DeferredItem<ThunderScroll> THUNDER_SCROLL = registerWithCTab("thunder_scroll", ThunderScroll::new);
    public static final DeferredItem<AbyssalHeart> ABYSSAL_HEART = registerWithCTab("abyssal_heart", AbyssalHeart::new);
    public static final DeferredItem<TheInfinitum> THE_INFINITUM = registerWithCTab("the_infinitum", TheInfinitum::new);
    public static final DeferredItem<EldritchAmulet> ELDRITCH_AMULET = registerWithCTab("eldritch_amulet", EldritchAmulet::new);
    public static final DeferredItem<DesolationRing> DESOLATION_RING = registerWithCTab("desolation_ring", DesolationRing::new);
    public static final DeferredItem<ViolenceScroll> VIOLENCE_SCROLL = registerWithCTab("violence_scroll", ViolenceScroll::new);
    public static final DeferredItem<ChaosElytra> CHAOS_ELYTRA = registerWithCTab("chaos_elytra", ChaosElytra::new);
    public static final DeferredItem<Item> ANNIHILATING_SWORD = registerWithCTab("annihilating_sword", BaseItem::Unknown);
    public static final DeferredItem<SoulCrystal> SOUL_CRYSTAL = registerWithTab("soul_crystal", SoulCrystal::new);
    public static final DeferredItem<StorageCrystal> STORAGE_CRYSTAL = ITEMS.register("storage_crystal", StorageCrystal::new);
    public static final DeferredItem<TheJudgement> THE_JUDGEMENT = ITEMS.register("the_judgement", TheJudgement::new);
    public static final DeferredItem<LootGenerator> LOOT_GENERATOR = ITEMS.register("loot_generator", LootGenerator::new);
    public static final DeferredItem<BaseItem> UNKNOWN = ITEMS.register("unknown", BaseItem::Unknown);

    protected static <T extends Item> @NotNull DeferredItem<T> registerWithTab(String id, Supplier<T> reg) {
        DeferredItem<T> register = ITEMS.register(id, reg);
        TAB_ACCEPT_LIST.add(register);
        return register;
    }
    protected static <T extends Item> @NotNull DeferredItem<T> registerWithCTab(String id, Supplier<T> reg) {
        DeferredItem<T> register = ITEMS.register(id, reg);
        CTAB_ACCEPT_LIST.add(register);
        return register;
    }

    static {
        IItemHelper.UNKNOWN_ITEMS.add(INFERNAL_FISHING_ROD);
        IItemHelper.UNKNOWN_ITEMS.add(ASTRAL_SPEAR);
        IItemHelper.UNKNOWN_ITEMS.add(BLESS_ITEM);
        IItemHelper.UNKNOWN_ITEMS.add(GRAIL);
        IItemHelper.UNKNOWN_ITEMS.add(FORGER_CRYSTAL);
        IItemHelper.UNKNOWN_ITEMS.add(ANNIHILATING_SWORD);
        IItemHelper.UNKNOWN_ITEMS.add(UNKNOWN);
    }
}
